<?php

return [
    'en' => [
        // Header & Navigation
        'products' => 'Products',
        'cart' => 'Cart',
        'orders' => 'Orders',
        'search' => 'Search products',
        'search_button' => 'Search',
        'my_orders' => 'My Orders',
        'profile' => 'Profile',
        'logout' => 'Logout',
        'login' => 'Login',
        'register' => 'Register',
        'contact_us' => 'Contact Us',
        'trusted_source' => 'Your trusted source for quality keychains',
        'email' => 'Email',
        'phone' => 'Phone',
        'language' => 'Language',

        // Home Page
        'welcome' => 'Welcome to Việt Nghệ Keychain',
        'featured_products' => 'Featured Products',
        'view_all' => 'View All',
        'latest_products' => 'Latest Products',
        'best_sellers' => 'Best Sellers',
        'previous' => 'Previous',
        'next' => 'Next',
        'view_details' => 'View Details',
        'free_shipping' => 'Free Shipping',
        'free_shipping_desc' => 'Free shipping on all orders over $50',
        'easy_returns' => 'Easy Returns',
        'easy_returns_desc' => '30-day return policy',
        'secure_payment' => 'Secure Payment',
        'secure_payment_desc' => 'Safe & secure payment methods',

        // Product Page
        'price' => 'Price',
        'color' => 'Color',
        'material' => 'Material',
        'add_to_cart' => 'Add to Cart',
        'quantity' => 'Quantity',
        'description' => 'Description',
        'specifications' => 'Specifications',
        'related_products' => 'Related Products',
        'categories' => 'Categories',
        'filter' => 'Filter',
        'sort_by' => 'Sort by',
        'price_low_high' => 'Price: Low to High',
        'price_high_low' => 'Price: High to Low',
        'newest' => 'Newest First',

        // Cart Page
        'your_cart' => 'Your Cart',
        'product' => 'Product',
        'subtotal' => 'Subtotal',
        'total' => 'Total',
        'update_cart' => 'Update Cart',
        'clear_cart' => 'Clear Cart',
        'continue_shopping' => 'Continue Shopping',
        'proceed_checkout' => 'Proceed to Checkout',
        'empty_cart' => 'Your cart is empty',
        'shopping_cart' => 'Shopping Cart',
        'available' => 'Available',
        'actions' => 'Actions',
        'remove' => 'Remove',
        'cart_items' => 'items in cart',

        // Checkout Page
        'checkout' => 'Checkout',
        'shipping_info' => 'Shipping Information',
        'payment_method' => 'Payment Method',
        'order_summary' => 'Order Summary',
        'place_order' => 'Place Order',
        'full_name' => 'Full Name',
        'address' => 'Address',
        'city' => 'City',
        'state' => 'State',
        'zip_code' => 'ZIP Code',
        'country' => 'Country',
        'phone_number' => 'Phone Number',

        // Orders Page
        'order_history' => 'Order History',
        'order_date' => 'Order Date',
        'order_status' => 'Status',
        'order_total' => 'Total',
        'view_order' => 'View Order',
        'order_details' => 'Order Details',
        'order_number' => 'Order Number',
        'shipping_address' => 'Shipping Address',
        'payment_details' => 'Payment Details',

        // Orders
        'no_orders_yet' => 'You haven\'t placed any orders yet.',
        'start_shopping' => 'Start shopping',
        'back_to_orders' => 'Back to Orders',
        'order_items' => 'Order Items',
        'order_information' => 'Order Information',
        'status_pending' => 'Pending',
        'status_processing' => 'Processing',
        'status_shipped' => 'Shipped',
        'status_delivered' => 'Delivered',
        'status_cancelled' => 'Cancelled',

        // Profile Page
        'personal_info' => 'Personal Information',
        'change_password' => 'Change Password',
        'save_changes' => 'Save Changes',
        'current_password' => 'Current Password',
        'new_password' => 'New Password',
        'confirm_password' => 'Confirm Password',
        'profile_updated_success' => 'Profile updated successfully.',
        'password_updated_success' => 'Password updated successfully.',
        'fill_required_fields' => 'Please fill in all required fields.',
        'update_failed' => 'Update failed. Please try again.',
        'general_error' => 'An error occurred. Please try again.',
        'email_cannot_change' => 'Email cannot be changed',
        'update_profile' => 'Update Profile',

        // Auth Pages
        'username' => 'Username',
        'first_name' => 'First Name',
        'last_name' => 'Last Name',
        'password_requirement' => 'Password must be at least 6 characters long',
        'sign_in' => 'Sign In',
        'sign_up' => 'Sign Up',
        'forgot_password' => 'Forgot Password?',
        'remember_me' => 'Remember Me',
        'already_account' => 'Already have an account?',
        'dont_account' => 'Don\'t have an account?',
        'password_reset' => 'Password Reset',
        'reset_password' => 'Reset Password',
        'username_or_email' => 'Username or Email',
        'invalid_credentials' => 'Invalid email/username or password',

        // Messages
        'success' => 'Success',
        'error' => 'Error',
        'warning' => 'Warning',
        'info' => 'Information',
        'confirm' => 'Confirm',
        'cancel' => 'Cancel',
        'delete' => 'Delete',
        'edit' => 'Edit',
        'save' => 'Save',
        'loading' => 'Loading...',
        'no_results' => 'No results found',
        'required_field' => 'This field is required',

        // Product Pages
        'search_results_for' => 'Search results for',
        'no_products_found' => 'No products found',
        'product_details' => 'Product Details',
        'stock' => 'Stock',
        'out_of_stock' => 'Out of stock',
        'back_to_products' => 'Back to Products',
    ],
    'vi' => [
        // Header & Navigation
        'products' => 'Sản phẩm',
        'cart' => 'Giỏ hàng',
        'orders' => 'Đơn hàng',
        'search' => 'Tìm kiếm sản phẩm',
        'search_button' => 'Tìm kiếm',
        'my_orders' => 'Đơn hàng của tôi',
        'profile' => 'Hồ sơ',
        'logout' => 'Đăng xuất',
        'login' => 'Đăng nhập',
        'register' => 'Đăng ký',
        'contact_us' => 'Liên hệ',
        'trusted_source' => 'Nguồn cung cấp móc khóa chất lượng đáng tin cậy',
        'email' => 'Email',
        'phone' => 'Điện thoại',
        'language' => 'Ngôn ngữ',

        // Home Page
        'welcome' => 'Chào mừng đến với Việt Nghệ Keychain',
        'featured_products' => 'Sản phẩm nổi bật',
        'view_all' => 'Xem tất cả',
        'latest_products' => 'Sản phẩm mới nhất',
        'best_sellers' => 'Sản phẩm bán chạy',
        'previous' => 'Trước',
        'next' => 'Tiếp',
        'view_details' => 'Xem chi tiết',
        'free_shipping' => 'Miễn phí vận chuyển',
        'free_shipping_desc' => 'Miễn phí vận chuyển cho đơn hàng trên 1.000.000₫',
        'easy_returns' => 'Đổi trả dễ dàng',
        'easy_returns_desc' => 'Chính sách đổi trả trong 30 ngày',
        'secure_payment' => 'Thanh toán an toàn',
        'secure_payment_desc' => 'Phương thức thanh toán an toàn và bảo mật',

        // Product Page
        'price' => 'Giá',
        'color' => 'Màu sắc',
        'material' => 'Chất liệu',
        'add_to_cart' => 'Thêm vào giỏ',
        'quantity' => 'Số lượng',
        'description' => 'Mô tả',
        'back_to_products' => 'Quay lại sản phẩm',
        'specifications' => 'Thông số kỹ thuật',
        'related_products' => 'Sản phẩm liên quan',
        'categories' => 'Danh mục',
        'filter' => 'Lọc',
        'sort_by' => 'Sắp xếp theo',
        'price_low_high' => 'Giá: Thấp đến cao',
        'price_high_low' => 'Giá: Cao đến thấp',
        'newest' => 'Mới nhất',

        // Cart Page
        'your_cart' => 'Giỏ hàng của bạn',
        'product' => 'Sản phẩm',
        'subtotal' => 'Tạm tính',
        'total' => 'Tổng cộng',
        'update_cart' => 'Cập nhật giỏ hàng',
        'clear_cart' => 'Xóa giỏ hàng',
        'continue_shopping' => 'Tiếp tục mua sắm',
        'proceed_checkout' => 'Tiến hành thanh toán',
        'empty_cart' => 'Giỏ hàng của bạn đang trống',
        'shopping_cart' => 'Giỏ hàng',
        'available' => 'Còn hàng',
        'actions' => 'Thao tác',
        'remove' => 'Xóa',
        'cart_items' => 'items in cart',

        // Checkout Page
        'checkout' => 'Thanh toán',
        'shipping_info' => 'Thông tin giao hàng',
        'payment_method' => 'Phương thức thanh toán',
        'order_summary' => 'Tóm tắt đơn hàng',
        'place_order' => 'Đặt hàng',
        'full_name' => 'Họ và tên',
        'address' => 'Địa chỉ',
        'city' => 'Thành phố',
        'state' => 'Tỉnh/Thành',
        'zip_code' => 'Mã bưu điện',
        'country' => 'Quốc gia',
        'phone_number' => 'Số điện thoại',

        // Orders Page
        'order_history' => 'Lịch sử đơn hàng',
        'order_date' => 'Ngày đặt hàng',
        'order_status' => 'Trạng thái',
        'order_total' => 'Tổng tiền',
        'view_order' => 'Xem đơn hàng',
        'order_details' => 'Chi tiết đơn hàng',
        'order_number' => 'Mã đơn hàng',
        'shipping_address' => 'Địa chỉ giao hàng',
        'payment_details' => 'Chi tiết thanh toán',

        // Orders
        'no_orders_yet' => 'Bạn chưa có đơn hàng nào.',
        'start_shopping' => 'Bắt đầu mua sắm',
        'back_to_orders' => 'Quay lại đơn hàng',
        'order_items' => 'Sản phẩm trong đơn',
        'order_information' => 'Thông tin đơn hàng',
        'status_pending' => 'Chờ xử lý',
        'status_processing' => 'Đang xử lý',
        'status_shipped' => 'Đã gửi hàng',
        'status_delivered' => 'Đã giao hàng',
        'status_cancelled' => 'Đã hủy',

        // Profile Page
        'personal_info' => 'Thông tin cá nhân',
        'change_password' => 'Đổi mật khẩu',
        'save_changes' => 'Lưu thay đổi',
        'current_password' => 'Mật khẩu hiện tại',
        'new_password' => 'Mật khẩu mới',
        'confirm_password' => 'Xác nhận mật khẩu',
        'profile_updated_success' => 'Cập nhật hồ sơ thành công.',
        'password_updated_success' => 'Cập nhật mật khẩu thành công.',
        'fill_required_fields' => 'Vui lòng điền đầy đủ thông tin bắt buộc.',
        'update_failed' => 'Cập nhật thất bại. Vui lòng thử lại.',
        'general_error' => 'Đã xảy ra lỗi. Vui lòng thử lại.',
        'email_cannot_change' => 'Không thể thay đổi email',
        'update_profile' => 'Cập nhật hồ sơ',

        // Auth Pages
        'username' => 'Tên đăng nhập',
        'first_name' => 'Tên',
        'last_name' => 'Họ',
        'password_requirement' => 'Mật khẩu phải có ít nhất 6 ký tự',
        'sign_in' => 'Đăng nhập',
        'sign_up' => 'Đăng ký',
        'forgot_password' => 'Quên mật khẩu?',
        'remember_me' => 'Ghi nhớ đăng nhập',
        'already_account' => 'Đã có tài khoản?',
        'dont_account' => 'Chưa có tài khoản?',
        'password_reset' => 'Đặt lại mật khẩu',
        'reset_password' => 'Đặt lại mật khẩu',
        'username_or_email' => 'Tên đăng nhập hoặc Email',
        'invalid_credentials' => 'Sai tên đăng nhập/email hoặc mật khẩu',

        // Messages
        'success' => 'Thành công',
        'error' => 'Lỗi',
        'warning' => 'Cảnh báo',
        'info' => 'Thông tin',
        'confirm' => 'Xác nhận',
        'cancel' => 'Hủy',
        'delete' => 'Xóa',
        'edit' => 'Sửa',
        'save' => 'Lưu',
        'loading' => 'Đang tải...',
        'no_results' => 'Không tìm thấy kết quả',
        'required_field' => 'Trường này là bắt buộc',

        // Product Pages
        'search_results_for' => 'Kết quả tìm kiếm cho',
        'no_products_found' => 'Không tìm thấy sản phẩm',
        'product_details' => 'Chi tiết sản phẩm',
        'stock' => 'Tồn kho',
        'out_of_stock' => 'Hết hàng',
        'back_to_products' => 'Quay lại sản phẩm',
    ]
];